### ISSUE TITLE
Schriftfarbe nicht lesbar

### ISSUE THREAD

**Issue by Phantomias2006** [thermo-Flaechenheizungs-GmbH/WLANThermoPCC#1]
Eine abgearbeitete Zeile kann nicht gelesen werden
![grafik](https://user-images.githubusercontent.com/15437240/44452718-8c0d7f00-a5f7-11e8-8b7a-6c5ad6e09894.png)

**Comment by becothas** [comment]
Wurde im aktuellen commit gelöst und wird in der nächsten Version enthalten sein.
