### ISSUE TITLE
Konfiguration laden/speichern

### ISSUE THREAD

**Issue by Phantomias2006** [thermo-Flaechenheizungs-GmbH/WLANThermoPCC#2]
![grafik](https://user-images.githubusercontent.com/15437240/44452968-38e7fc00-a5f8-11e8-8966-4d718ef5b622.png)

Im gelb markierten Bereich bitte eine Öffnen/Speichern funktion einbauen.
Diese Button's können ruhig etwas mehr abstand zu den darüber liegenden Icons haben.
Gespeichert werden soll:
Temp
Seconds

**Comment by becothas** [comment]
Add functionality. Will be in next release.
