### ISSUE TITLE
Sollwertabsenkung funktioniert nicht

### ISSUE THREAD

**Issue by thermo-GmbH** [thermo-Flaechenheizungs-GmbH/WLANThermoPCC#3]
Wie man in den gelb markierten Bereichen sieht, wird ein niedrigerer Sollwert nicht abgearbeitet.

![test_pcc_release_0 4](https://user-images.githubusercontent.com/41284608/44454344-887bf700-a5fb-11e8-8048-155dd63f582a.jpg)

**Comment by becothas** [comment]
Funktion wird in die nächste Version aufgenommen.
