### ISSUE TITLE
Abkühlphase (kleinerer Sollwert) mit negativer "Heating Time" anzeigen

### ISSUE THREAD

**Issue by thermo-GmbH** [thermo-Flaechenheizungs-GmbH/WLANThermoPCC#4]
Abkühlphase mit negativer "Heating Time" anzeigen, dadurch weiß man auch wie lange die Phase gedauert hat.

![image](https://user-images.githubusercontent.com/41284608/44454581-28d21b80-a5fc-11e8-9a95-6baa08ec0567.png)

**Comment by becothas** [comment]
Funktion wird in die nächste Version aufgenommen.
