### ISSUE TITLE
"Load from File"

### ISSUE THREAD

**Issue by thermo-GmbH** [thermo-Flaechenheizungs-GmbH/WLANThermoPCC#6]
Wenn man "Load from file" macht, wird das Tool geschlossen.

**Comment by becothas** [comment]
Wo genau liegt das Problem beim Lesen der Datei ? 
Wurde die Datei vorher vom WLANThermo PCC erzeugt? 
Passiert dies bei jeder Datei, wenn nein, bitte Datei hochladen.

**Comment by thermo-GmbH** [comment]
Habe es gerade nochmal ausprobiert und mit einem neu gestartetem Tool funktioniert das Laden eines Files.
Offensichtlich hatte ich damals noch Werte in der Tabelle drin. Ich dachte, man kann einfach neue Werte aus einem anderen Test laden und die bestehenden Werte überschreiben, aber genau dann schließt das Tool.
Wenn ich das weiss, ist das auch ok, das Tool ist ja schnell wieder gestartet.

**Comment by thermo-GmbH** [comment]
Halt, mit diesem File geht es nicht! Es wurde auch mit dem Tool erzeugt:
[test1.zip](https://github.com/thermo-Flaechenheizungs-GmbH/WLANThermoPCC/files/2370077/test1.zip)

**Comment by thermo-GmbH** [comment]
Ich denke, ich habe das Problem gefunden. In der test1.ini ist eine Temperatur mit Dezimalstelle drin, wenn ich die rauslösche, kann ich die Tabelle laden.

[test1.zip](https://github.com/thermo-Flaechenheizungs-GmbH/WLANThermoPCC/files/2370072/test1.zip)

**Comment by becothas** [comment]
Vielen Dank für die Information. Kann es sein dass die test1.xlsx versehentlich hochgeladen wurde ? 
Weil hiermit wird es definitiv nicht funktionieren. 
Werde mich die nächsten Tage mit einem Update melden wo dieser Fehler behoben wird.

**Comment by thermo-GmbH** [comment]
Ja, die test1.xls war ein versehen, habe ich mittlerweile auch schon geändert :-)

**Comment by becothas** [comment]
Habe den Fehler gelöst. Das Laden von Datein mit kommawerten ist nun möglich.
