### ISSUE TITLE
Re-Start PITmaster

### ISSUE THREAD

**Issue by thermo-GmbH** [thermo-Flaechenheizungs-GmbH/WLANThermoPCC#7]
Nach einem Stopp des Programmablaufs und anschließendem erneutem "Start" kommt die Meldung "Pitmaster" gestartet aber der PIT ist aus und der Sollwert ist bei 20 Grad.

**Comment by becothas** [comment]
Bei einem erneuten Starten des Pitmasters, wird jetzt der vorherige Durchgang rückgesetzt und erneut gestartet.
Habe leider aktuell kein Gerät zum Testen, also bitte durchtesten und wenn's funktioniert bitte das Ticket schließen.

**Comment by thermo-GmbH** [comment]
Nach einem Stop wird der Pimaster auf den ersten Wert zurückgesetzt und nicht auf den Vorherigen.
Es erfolgt dann CoolingDown.
Dass der Programmablauf gestoppt wurde kann man nur daran erkennen, dass "heating time"und die "time left" Zeit steht ==> ggf. Eintrag in den Staus als "stopped" oder so möglich? 

![1unbenannt](https://user-images.githubusercontent.com/41284608/45620720-18d41d00-ba7e-11e8-92aa-e8f02ce76c05.JPG)

![2unbenannt](https://user-images.githubusercontent.com/41284608/45620730-1f629480-ba7e-11e8-9f63-82b0ccd5b9e7.JPG)

![3unbenannt](https://user-images.githubusercontent.com/41284608/45620734-25f10c00-ba7e-11e8-8eb5-c8333b72c2be.JPG)

**Comment by becothas** [comment]
Mit "vorherigen Durchgang rücksetzen" habe ich genau gemeint, dass die komplette vorherige Messung zurückgesetzt wird und wieder beim ersten Eintrag in der Liste begonnen wird. 
Habe nur beim rücksetzen die HeatingTime vergessen --> ist in v0.7 enthalten.
Bitte wieder testen und Ticket schließen.
Man erkennt auch ob der Pitmaster gestartet ist am Start/Stopknopf hier ändert sich das Symbol von einem Dreieck auf ein Quadrat. 
Dreieck ... Pitmaster ist gestoppt 
Quadrat ... Pitmaster läuft. 
Für neue Wünsche und Bugreports keine bestehenden Tickets missbrauchen.

**Comment by thermo-GmbH** [comment]
Überprüft und O.K.
